Config = {}

Config.Services = {
    ['staff'] = "ticket.permissao",
    ['médico'] = "perm.chamadoshp",
    ['mecânico'] = "perm.chamadomec",
    ['policia'] = "perm.policia",
}

Config.Tips = {
    -- TIPOS DE CATEGORIAS
    -- tips: 'Dicas Iniciais',
    -- howToStart: 'Como começar',
    -- earnMoney: 'GANHE DINHEIRO',
    -- factions: 'Facções',
    -- commonBugs: 'Bugs comuns',
    -- updates: 'Atualizações',
    -- orgs: 'Organizações',
    {
        title = 'Novidade #1',
        description = 'Pesca AFK',
        image = 'https://r2.fivemanage.com/pub/0wunrv1fxen4.png',
        link = 'https://www.youtube.com/embed/21UBf2uph7Q',
        category = 'updates', 
    },
    {
        title = 'Novidade #2',
        description = 'Cooldown de 1 minuto',
        image = 'https://r2.fivemanage.com/pub/kkguqwitcwxz.png',
        link = 'https://www.youtube.com/embed/EcM1zmNKcAw',
        category = 'updates',
    },
    {
        title = 'Novidade #3',
        description = 'Script PVP',
        image = 'https://r2.fivemanage.com/pub/g3i3ph94vwf5.png',
        link = 'https://www.youtube.com/embed/zP8rLTQsy4M',
        category = 'updates',
    },
    {
        title = 'Ganhe Dinheiro #1',
        description = 'Emprego de Laranjas',
        image = 'https://r2.fivemanage.com/pub/hy9zz1k928ob.png',
        link = 'https://www.youtube.com/embed/ZDVfqJEy4bM',
        category = 'howToStart',
    },
    {
        title = 'Ganhe Dinheiro #2',
        description = 'Emprego de Minerador',
        image = 'https://r2.fivemanage.com/pub/7ff1d1tve18c.png',
        link = 'https://www.youtube.com/embed/rMQLRQNjNDU',
        category = 'howToStart',
    },
    {
        title = 'Ganhe Dinheiro #3',
        description = 'Emprego de Entregador',
        image = 'https://r2.fivemanage.com/pub/onm6yj8rlvmn.png',
        link = 'https://www.youtube.com/embed/H4KXkEZ-RDw',
        category = 'howToStart',
    },
    {
        title = 'Ganhe Dinheiro #4',
        description = 'Emprego de Tomate',
        image = 'https://r2.fivemanage.com/pub/nrhitjpc8m71.png',
        link = 'https://www.youtube.com/embed/Gb19wizPkoQ',
        category = 'howToStart',
    },
    {
        title = 'Ganhe Dinheiro #5',
        description = 'Emprego de Eletricista',
        image = 'https://r2.fivemanage.com/pub/so88qvf95iad.png',
        link = 'https://www.youtube.com/embed/mv_KTwuug-g',
        category = 'howToStart',
    },
    {
        title = 'Facção #1',
        description = 'Facção de Munição',
        image = 'https://r2.fivemanage.com/pub/so88qvf95iad.png',
        link = '<iframe width="560" height="315" src="https://www.youtube.com/embed/8hMJNF7Ze5M?si=Ewi5t2mhCs0BMhsI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        category = 'factions',
    },
    {
        title = 'Facção #2',
        description = 'Facção de Lavagem',
        image = 'https://r2.fivemanage.com/pub/so88qvf95iad.png',
        link = '<iframe width="560" height="315" src="https://www.youtube.com/embed/dJpqHzfIcvs?si=yNGFoDqAOnemk4D9" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        category = 'factions',
    },
    {
        title = 'Facção #3',
        description = 'Facção de Drogas',
        image = 'https://r2.fivemanage.com/pub/so88qvf95iad.png',
        link = '<iframe width="560" height="315" src="https://www.youtube.com/embed/MQY8x_UyoZ8?si=bdynHiB3gThqHS6C" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        category = 'factions',
    },
    {
        title = 'Facção #4',
        description = 'Facção de Desmanche',
        image = 'https://r2.fivemanage.com/pub/so88qvf95iad.png',
        link = '<iframe width="560" height="315" src="https://www.youtube.com/embed/MQY8x_UyoZ8?si=9VWcMl3HXptRx_4f" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        category = 'factions',
    },
    {
        title = 'Facção #5',
        description = 'Facção de Armas',
        image = 'https://r2.fivemanage.com/pub/so88qvf95iad.png',
        link = '<iframe width="560" height="315" src="https://www.youtube.com/embed/xAeFJUw6ScU?si=ZqwlDuRf7M6zOKJK" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        category = 'factions',
    },
    {
        title = 'Organização #1',
        description = 'Polícia',
        image = 'https://r2.fivemanage.com/pub/so88qvf95iad.png',
        link = '<iframe width="560" height="315" src="https://www.youtube.com/embed/8K0j1pWR7Y4?si=JPyw1wF4ourfYMAL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        category = 'orgs',
    },
    {
        title = 'Organização #2',
        description = 'Mecânica',
        image = 'https://r2.fivemanage.com/pub/so88qvf95iad.png',
        link = '<iframe width="560" height="315" src="https://www.youtube.com/embed/FgidjWm5eeQ?si=HfiD7_h2cLoN8E1o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        category = 'orgs',
    },
    {
        title = 'Organização #3',
        description = 'Jurídico',
        image = 'https://r2.fivemanage.com/pub/so88qvf95iad.png',
        link = '<iframe width="560" height="315" src="https://www.youtube.com/embed/fiZjGvrBUyY?si=CmuMDg2S3hHfr4ap" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        category = 'orgs',
    },
    {
        title = 'Organização #4',
        description = 'Hospital',
        image = 'https://r2.fivemanage.com/pub/so88qvf95iad.png',
        link = '<iframe width="560" height="315" src="https://www.youtube.com/embed/_BcpPPWLo8Q?si=hxZ9QWL-fF3qMoHU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        category = 'orgs',
    },
    {
        title = 'Organização #5',
        description = 'Bombeiro',
        image = 'https://r2.fivemanage.com/pub/so88qvf95iad.png',
        link = '<iframe width="560" height="315" src="https://www.youtube.com/embed/-QmmJO3EVTE?si=uH6S7jUY-g9Su7rN" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>',
        category = 'orgs',
    },
}