Vips = {
    { permission = "perm.vagas5", discount = 0, maxCars = 5 },
    { permission = "perm.vagas10", discount = 0, maxCars = 10 },
    { permission = "perm.vagas11", discount = 0, maxCars = 11 },
    { permission = "perm.vagas12", discount = 0, maxCars = 12 },
    { permission = "perm.vagas15", discount = 0, maxCars = 15 },
    { permission = "perm.vagas32", discount = 0, maxCars = 32 },
    { permission = "perm.vagas30", discount = 0, maxCars = 30 },
    { permission = "perm.vagas19", discount = 0, maxCars = 19 },
    { permission = "perm.vagas36", discount = 0, maxCars = 36 },
    
    { permission = "perm.vagastres", discount = 0, maxCars = 3 },
    { permission = "perm.vipcopa", discount = 5, maxCars = 5 },

    { permission = "perm.011rp", discount = 40 , maxCars = 30 },
    { permission = "perm.bronze", discount = 5, maxCars = 3 },
    { permission = "perm.prata", discount = 5, maxCars = 5 },
    { permission = "perm.ouro", discount = 9, maxCars = 8 },
    { permission = "perm.platina", discount = 9 , maxCars = 8 },
    { permission = "perm.diamante", discount = 13 , maxCars = 15 },
    { permission = "perm.esmeralda", discount = 13 , maxCars = 15 }, 
    { permission = "perm.safira", discount = 25 , maxCars = 25 },
    { permission = "perm.rubi", discount = 30 , maxCars = 30 },
    { permission = "perm.capitalrj", discount = 40 , maxCars = 30 },
    { permission = "perm.supremocapital", discount = 50 , maxCars = 100 },
    { permission = "perm.vipsetembro", discount = 35 , maxCars = 25 },
    { permission = "perm.vipblackfriday", discount = 50, maxCars = 25},
    { permission = "perm.vippascoa", discount = 50, maxCars = 25},
    { permission = "perm.vip2025", discount = 50, maxCars = 25},
    { permission = "perm.vipcrianca", discount = 50 , maxCars = 5 },
    { permission = "perm.viphalloween", discount = 50 , maxCars = 50 },
    { permission = "perm.vipnatal", discount = 50 , maxCars = 50 },
    { permission = "perm.vipanonovo", discount = 50 , maxCars = 50 },
    { permission = "perm.vipcarnaval", discount = 50 , maxCars = 50 },
    { permission = "perm.vipmaio", discount = 50 , maxCars = 50 },
    { permission = "perm.pascoa", discount = 50, maxCars = 50 },
    { permission = "perm.ferias", discount = 50, maxCars = 50 },
    { permission = "perm.vipwipe", discount = 50, maxCars = 0 },
    { permission = "perm.vipreal", discount = 50, maxCars = 50 },
    { permission = "perm.olimpiadas", discount = 50, maxCars = 50 },
    { permission = "perm.vipsaojoao", discount = 35, maxCars = 25 },
    { permission = "perm.vipverao", discount = 50, maxCars = 50 },
    { permission = "perm.vipoutono", discount = 50, maxCars = 50 },
}