config = {
    vipGroups = {
        "Bronze",
        "Prata",
        "Ouro",
        "Platina",
        "Diamante",
        "Esmeralda",
        "Safira",
        "Rubi",
        "Capitalrj",
        "SupremoCapital",
        "Pascoa",
        "VipHalloween",
        "VipDeluxe",
        "VipReal",
        "Olimpiada",
        "VipIndependencia",
        "Ferias",
        "VipPolicia",
        "VipMedico",
        "VipBombeiro",
        "VipMecanico",
        "VipSaoJoao",
        "VipCrianca",
        "VipSetembro",
        "VipVerao",
        "VipCarnaval",
        "VipOutono",
        "VipMaio",
        "VipNatal",
        "Vip2025",
        "VipMakakero",
        "VipInauguracao",
        "VipAnoNovo",
        "VipInicial",
        "VipBlackfriday",
        "VipPascoa",
    },
    package = {
        title = 'PACK PORSCHE',
        description = 'PORSCHE 911R - PORSCHE TAYCAN21 - PORSCHE MACAN-T',
        price = 6800,
        items = {
            { spawn = '911r', name = 'PORSCHE 911R', price = 2260 },
            { spawn = 'taycan21', name = 'PORSCHE TAYCAN21', price = 2260 },
            { spawn = 'macanturbo', name = 'PORSCHE MACAN-T', price = 2260 },
        }
    },
    stores = {
        { spawn = '350z', name = '350Z', price = 800},
        { spawn = 'wrrelampagomarquinhos', name = 'Mini Relampago Marquinhos', price = 1200},
        { spawn = '23teslapf', name = 'Tesla PF', price = 2000},
        { spawn = '22g63', name = 'G63', price = 2000},
        { spawn = 'd99', name = 'DUCATTI 99R', price = 2000},
    },
}